permissions:
  contents: read
on:
  push:
    branches: [dev]
  pull_request:
defaults:
  run:
    shell: wsl-bash {0}
name: check-wsl
jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Setup WSL
        uses: Vampire/setup-wsl@v3.1.1
      - name: install fortran compiler
        run: sudo apt install -y gfortran
