permissions:
  contents: read
on:
  push:
    branches: [dev]
  pull_request:
defaults:
  run:
    shell: wsl-bash {0}
name: check-wsl
jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Setup WSL
        uses: Vampire/setup-wsl@v3.1.1
      - name: install fortran compiler
        run: sudo apt update -y && sudo apt upgrade -y && sudo apt install -y gfortran
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo check
        run: cargo check
